services:
  - type: web
    name: frontend
    plan: starter
    runtime: node
    buildCommand: |
      npm install
      npm run build --workspace=@course-project/shared
      npm run build --workspace=@course-project/frontend
    startCommand: npm start --workspace=@course-project/frontend

  - type: web
    name: backend
    plan: starter
    runtime: node
    buildCommand: |
      npm install
      npm run build --workspace=@course-project/shared
      npm run build --workspace=@course-project/backend
    startCommand: npm start --workspace=@course-project/backend
