export const forms = [
  {
    id: '1',
    title: 'Sample Form',
    author_id: 'lollo',
    likes: 5,
    created_at: '12-11-1111',
    fields: [
      {
        id: '1',
        type: 'text',
        label: 'What is your name?',
        placeholder: 'Enter your name',
      },
      {
        id: '2',
        type: 'textarea',
        label: 'Tell us about yourself',
        placeholder: 'Write something...',
      },
      {
        id: '3',
        type: 'radio',
        label: 'What is your favorite color?',
        options: ['Red', 'Blue', 'Green'],
      },
      {
        id: '4',
        type: 'checkbox',
        label: 'What are your hobbies?',
        options: ['Reading', 'Traveling', 'Cooking'],
      },
    ],
  },
  {
    id: '2',
    title: 'Sample Form 2',
    author_id: 'lollo',
    likes: 5,
    created_at: '12-11-1111',
    fields: [
      {
        id: '1',
        type: 'text',
        label: 'What is your name?',
        placeholder: 'Enter your name',
      },
      {
        id: '2',
        type: 'textarea',
        label: 'Tell us about yourself',
        placeholder: 'Write something...',
      },
      {
        id: '3',
        type: 'radio',
        label: 'What is your favorite color?',
        options: ['Red', 'Blue', 'Green'],
      },
      {
        id: '4',
        type: 'checkbox',
        label: 'What are your hobbies?',
        options: ['Reading', 'Traveling', 'Cooking'],
      },
    ],
  },
  {
    id: '3',
    title: 'Sample Form 3',
    author_id: 'lollo',
    likes: 5,
    created_at: '12-11-1111',
    fields: [
      {
        id: '1',
        type: 'text',
        label: 'What is your name?',
        placeholder: 'Enter your name',
      },
      {
        id: '2',
        type: 'textarea',
        label: 'Tell us about yourself',
        placeholder: 'Write something...',
      },
      {
        id: '3',
        type: 'radio',
        label: 'What is your favorite color?',
        options: ['Red', 'Blue', 'Green'],
      },
      {
        id: '4',
        type: 'checkbox',
        label: 'What are your hobbies?',
        options: ['Reading', 'Traveling', 'Cooking'],
      },
    ],
  },
  {
    id: '4',
    title: 'Sample Form 4',
    author_id: 'lollo',
    likes: 5,
    created_at: '12-11-1111',
    fields: [
      {
        id: '1',
        type: 'text',
        label: 'What is your name?',
        placeholder: 'Enter your name',
      },
      {
        id: '2',
        type: 'textarea',
        label: 'Tell us about yourself',
        placeholder: 'Write something...',
      },
      {
        id: '3',
        type: 'radio',
        label: 'What is your favorite color?',
        options: ['Red', 'Blue', 'Green'],
      },
      {
        id: '4',
        type: 'checkbox',
        label: 'What are your hobbies?',
        options: ['Reading', 'Traveling', 'Cooking'],
      },
    ],
  },
  {
    id: '5',
    title: 'Sample Form 5',
    author_id: 'lollo',
    likes: 5,
    created_at: '12-11-1111',
    fields: [
      {
        id: '1',
        type: 'text',
        label: 'What is your name?',
        placeholder: 'Enter your name',
      },
      {
        id: '2',
        type: 'textarea',
        label: 'Tell us about yourself',
        placeholder: 'Write something...',
      },
      {
        id: '3',
        type: 'radio',
        label: 'What is your favorite color?',
        options: ['Red', 'Blue', 'Green'],
      },
      {
        id: '4',
        type: 'checkbox',
        label: 'What are your hobbies?',
        options: ['Reading', 'Traveling', 'Cooking'],
      },
    ],
  },
  {
    id: '6',
    title: 'Sample Form',
    author_id: 'lollo',
    likes: 5,
    created_at: '12-11-1111',
    fields: [
      {
        id: '1',
        type: 'text',
        label: 'What is your name?',
        placeholder: 'Enter your name',
      },
      {
        id: '2',
        type: 'textarea',
        label: 'Tell us about yourself',
        placeholder: 'Write something...',
      },
      {
        id: '3',
        type: 'radio',
        label: 'What is your favorite color?',
        options: ['Red', 'Blue', 'Green'],
      },
      {
        id: '4',
        type: 'checkbox',
        label: 'What are your hobbies?',
        options: ['Reading', 'Traveling', 'Cooking'],
      },
    ],
  },
  {
    id: '7',
    title: 'Sample Form 2',
    author_id: 'lollo',
    likes: 5,
    created_at: '12-11-1111',
    fields: [
      {
        id: '1',
        type: 'text',
        label: 'What is your name?',
        placeholder: 'Enter your name',
      },
      {
        id: '2',
        type: 'textarea',
        label: 'Tell us about yourself',
        placeholder: 'Write something...',
      },
      {
        id: '3',
        type: 'radio',
        label: 'What is your favorite color?',
        options: ['Red', 'Blue', 'Green'],
      },
      {
        id: '4',
        type: 'checkbox',
        label: 'What are your hobbies?',
        options: ['Reading', 'Traveling', 'Cooking'],
      },
    ],
  },
  {
    id: '8',
    title: 'Sample Form 3',
    author_id: 'lollo',
    created_at: '12-11-1111',
    likes: 5,
    fields: [
      {
        id: '1',
        type: 'text',
        label: 'What is your name?',
        placeholder: 'Enter your name',
      },
      {
        id: '2',
        type: 'textarea',
        label: 'Tell us about yourself',
        placeholder: 'Write something...',
      },
      {
        id: '3',
        type: 'radio',
        label: 'What is your favorite color?',
        options: ['Red', 'Blue', 'Green'],
      },
      {
        id: '4',
        type: 'checkbox',
        label: 'What are your hobbies?',
        options: ['Reading', 'Traveling', 'Cooking'],
      },
    ],
  },
  {
    id: '9',
    title: 'Sample Form 4',
    author_id: 'lollo',
    created_at: '12-11-1111',
    likes: 5,
    fields: [
      {
        id: '1',
        type: 'text',
        label: 'What is your name?',
        placeholder: 'Enter your name',
      },
      {
        id: '2',
        type: 'textarea',
        label: 'Tell us about yourself',
        placeholder: 'Write something...',
      },
      {
        id: '3',
        type: 'radio',
        label: 'What is your favorite color?',
        options: ['Red', 'Blue', 'Green'],
      },
      {
        id: '4',
        type: 'checkbox',
        label: 'What are your hobbies?',
        options: ['Reading', 'Traveling', 'Cooking'],
      },
    ],
  },
  {
    id: '10',
    title: 'Sample Form 5',
    author_id: 'lollo',
    likes: 5,
    created_at: '12-11-1111',
    fields: [
      {
        id: '1',
        type: 'text',
        label: 'What is your name?',
        placeholder: 'Enter your name',
      },
      {
        id: '2',
        type: 'textarea',
        label: 'Tell us about yourself',
        placeholder: 'Write something...',
      },
      {
        id: '3',
        type: 'radio',
        label: 'What is your favorite color?',
        options: ['Red', 'Blue', 'Green'],
      },
      {
        id: '4',
        type: 'checkbox',
        label: 'What are your hobbies?',
        options: ['Reading', 'Traveling', 'Cooking'],
      },
    ],
  },
];